language: scala
sudo: true
dist: trusty

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

jdk:
  - openjdk8

notifications:
  email:
    - joshua.suereth@typesafe.com

script:
  - sbt -J-XX:ReservedCodeCacheSize=128m "+test"

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
